### PR TITLE
Updating to protobuf definition from API release version 1.23.0

### LINKED ISSUE #1746: Add capability and SDK metadata field for test server
**Describe the solution you'd like**

Need support for https://github.com/temporalio/api/pull/259 and https://github.com/temporalio/api/pull/263

### PR DESCRIPTION
**Pull request by edmondop**
## What was changed

Addresses #1746 re-pointing the submodule to the commit of https://github.com/temporalio/api/releases/tag/v1.23.0

## Checklist

1. Closes 

2. How was this tested:

3. Any docs updates needed?

### CODE REVIEW

**Comment by Quinn-With-Two-Ns** [comment]
API should already be at 1.23.0 from this commit https://github.com/temporalio/sdk-java/commit/c215a78b55020bec7f67b31c0dd8c62bcc007f62#diff-d1eb76f6f4c6f3b8ac68ddec9f32eeb7874e4c753220a41b5145c8e771ab0e7a

**Comment by edmondop** [comment]
I see that the proto folder has been updated in the PR, but the .gitsubmodule hexsha hasn't. Is that expected?

**Comment by Quinn-With-Two-Ns** [comment]
To be honest I am not familiar with why any `hexsha`  value is in the `.gitmodules` because I don't think it does anything https://git-scm.com/docs/gitmodules

**Comment by Quinn-With-Two-Ns** [comment]
Closing this PR as https://github.com/temporalio/sdk-java/pull/1800 already updated the API release version

**Pull request closed without merging**
