### PR TITLE
Added workflow retry policy propagation during continue-as-new and to ContinueAsNewOptions.

### PR DESCRIPTION
**Pull request by mfateev**
## What was changed
After this change if a worklfow has RetryOptions configured then they are copied to the continued workflow.

Added RetryOptions to ContinueAsNewOptions to allow overriding them when calling contineu-as-new.

Added WorkflowInfo.getRetryOptions to give access to the options from the worklfow code.

## Why?
Currently there is no ability to specify retry options to the next workflow execution when calling continue-as-new.

### CODE REVIEW

**Review by Quinn-With-Two-Ns — APPROVED** [review]
Thanks for this,

Technically this is a backwards incompatible change, but we where OK with it in the Go SDK so I see no reason not to allow it here.

**Comment by Quinn-With-Two-Ns** [comment]
closes https://github.com/temporalio/sdk-java/issues/1959

**Comment by Quinn-With-Two-Ns** [comment]
related https://github.com/temporalio/sdk-java/issues/1201

**Comment by MatthewHou** [comment]
@mfateev Thank you for the fix! I have tested out your change locally and noticed 2 things:
1.  An empty `ContinueAsNewOptions` needs to be provided when calling `continueAsNew` for the default `RetryOptions` to be copied over. This seems to be related to the null check [here](https://github.com/temporalio/sdk-java/pull/1961/files#diff-0dd6530b3cbc81275990c91ae5132c38067aea036893ae87771134ed23b60eb4R1099). I'm not sure if this the expected behaviour. 
2. The retry attempt count resets to 1 in the continued workflow. I guess this is a server side bug related to this issue? 
https://github.com/temporalio/temporal/issues/5249

**Comment by mfateev** [comment]
@MatthewHou 

1. Good catch. I've updated the PR to copy RetryOptions on empty ContinueAsNewOptions. 
2. This is by design, as retries are reset on each continue-as-new.

**Pull request merged**
