### PR TITLE
add WorkflowImplementationOptions customizer

### PR DESCRIPTION
**Pull request by antmendoza**
## What was changed

Allow set `WorkflowImplementationOptions` using customizer 
https://github.com/temporalio/sdk-java/tree/master/temporal-spring-boot-autoconfigure-alpha#customization-of-options

## Checklist

1. Closes 

2. How was this tested:

3. Any docs updates needed?

### CODE REVIEW

**Review by Quinn-With-Two-Ns — COMMENTED** [review]
Sorry for the late review, was OOTO and then traveling.

LGTM, you have some CI error could you address them? then I will approve.

**Comment by antmendoza** [comment]
@Quinn-With-Two-Ns I think it is done now, sorry I didn't notice it failed

**Comment by antmendoza** [comment]
@Quinn-With-Two-Ns ^^ :)

**Review by Quinn-With-Two-Ns — APPROVED** [review]

**Comment by Quinn-With-Two-Ns** [comment]
@antmendoza Sorry about that thought I approved when I enabled auto-merge.

**Comment by antmendoza** [comment]
no problem, thanks :)

**Pull request merged**
