### PR TITLE
Properly wrap exceptions from schedule client

### PR DESCRIPTION
**Pull request by Quinn-With-Two-Ns**
Wrap exceptions from the `ScheduleClient`. Add some tests to show the exception is wrapped

### CODE REVIEW

**Comment by cretz** [comment]
I feel like I remember us discussing this somewhere, but I forget the details. I wonder if we need to do this in other SDKs.

**Comment by Quinn-With-Two-Ns** [comment]
This is more java specific because java SDK always wraps all  the exceptions it throws. I don't think other SDKs try to.

**Comment by mjameswh** [comment]
> This is more java specific because java SDK always wraps all the exceptions it throws. I don't think other SDKs try to.

We do in TS.

You should test that non-schedules related errors (like [namespace not found](https://github.com/temporalio/sdk-typescript/issues/1145)) don't get wrapped as `ScheduleException`. In TS, we now parse the `grpc-status-details-bin` metadata on errors (see [PR](https://github.com/temporalio/sdk-typescript/pull/1147)), which makes proper error reporting significantly easier.

**Review by cretz — APPROVED** [review]

**Comment by Quinn-With-Two-Ns** [comment]
@mjameswh I think typescript is unique in having a `NamespaceNotFound` exception. I don't think Java or Dotnet has it (didn't check python).

@cretz I remember on the original PR I had `ScheduleNotFound` exception but we removed it because the server did not send enough status details for us to disambiguate on the SDK side?

**Comment by cretz** [comment]
> because the server did not send enough status details for us to disambiguate on the SDK side?

Right, but server gives enough information for namespace not found. We do have namespace not found in Go, but yes probably not the newer non-TS core SDKs

**Pull request merged**
