### PR TITLE
Support generics on workflow methods

### PR DESCRIPTION
**Pull request by rorueda**
## What was changed

Support for generics on workflow methods, both in parameters and return types. The aim is to support use cases like the following:

1. Use of a `TypeVariable` that is specified.
```java
public interface QueryBase<T> {
  @QueryMethod
  T query();
}
@WorkflowInterface
public interface Workflow extends QueryBase<WorkflowState> {}
```

2. Use of a `TypeVariable` that is bound.
```java
public interface QueryBase<T> {
  @QueryMethod
  T query();
}
@WorkflowInterface
public interface Workflow<T extends WorkflowState> extends QueryBase<T> {}
```

3. Use of a `TypeVariable` in a `ParameterizedType`.
```java
public interface QueryBase<T> {
  @QueryMethod
  Wrapper<T> query();
}
@WorkflowInterface
public interface Workflow extends QueryBase<WorkflowState> {}
```

4. Use of a `TypeVariable` in a `GenericArrayType`.
```java
public interface QueryBase<T> {
  @QueryMethod
  T[] query();
}
@WorkflowInterface
public interface Workflow extends QueryBase<WorkflowState> {}
```

5. Use of a `TypeVariable` in a `GenericArrayType`, in a `ParameterizedType`.
```java
public interface QueryBase<T> {
  @QueryMethod
  Wrapper<T[]> query();
}
@WorkflowInterface
public interface Workflow extends QueryBase<WorkflowState> {}
```

6. Use of a `TypeVariable` as an upper bound of a `WildcardType` in a `ParameterizedType`.
```java
public interface QueryBase<T> {
  @QueryMethod
  Wrapper<? extends T> query();
}
@WorkflowInterface
public interface Workflow extends QueryBase<WorkflowState> {}
```

## Why?

To be able to reuse a base interface in all my workflow interfaces. Together, the two issues mentioned below in the checklist make this currently impossible.

Reading the comments on the first issue, I get that this support might be controversial, but I couldn't live without it. It would be great to have this merged, so others can benefit and I don't need to keep a fork.

## Checklist

1. Closes 
https://github.com/temporalio/sdk-java/issues/1106
https://github.com/temporalio/sdk-java/issues/1107
2. How was this tested:

Unit tests.

3. Any docs updates needed?

Maybe it is good to point out what is supported at [workflow-parameters](https://docs.temporal.io/develop/java/core-application#workflow-parameters) and [workflow-return-values](https://docs.temporal.io/develop/java/core-application#workflow-return-values).

### CODE REVIEW

**Comment by Quinn-With-Two-Ns** [comment]
Hey @rorueda Thank you for the contribution. First impression it looks good, but I need to take a closer look over a couple days to verify and make sure we aren't breaking any existing user. Can you think of any existing cases that may break from this change?

**Comment by rorueda** [comment]
Great, @Quinn-With-Two-Ns. 

I certainly hope this doesn't break existing code, or at least break during startup, instead of resulting in wrong deserialization, because the changes made shouldn't result in already fully resolved types, with no type variables, being modified. 

I made some minor, I think, changes to try to encapsulate more stuff inside the `POJOWorkflowMethod`, but I would expect it to be covered by existing tests. 

I am not sure, but people who use native images might need to take additional steps to make this work. 

For people that will start using generics, the `PayloadConverter.fromData` will receive a different `valueType`, that is usually passed on to the serialization library, but a custom `PayloadConverter` might not do this for whatever reason or the serialization library might not handle the complex types well.

That is all I can think at the moment.

PS: I see that the features test is broken because of one of the changes and I'll push a fix.

**Comment by rorueda** [comment]
So, there were 2 issues with the features test:
- I've changed the return type of a method in `POJOWorkflowMethodMetadata` that is used in the runner. Even though it is a public method, I assumed it's kind of internal;
- At least one method on the workflow interfaces there was declaring a type variable. It's just a helper method it seems, but as it's a candidate for turning into a workflow method, it is processed and the code was not handling this situation.

I'd like to keep the change to `POJOWorkflowMethodMetadata` because I think it is best long-term, but it would require the features to be compiled against the modified sdk. Does the CI modifies the `features/build.gradle` to use the sdk snaphost? If not, will probably have to keep the old method and add a new one.

**Comment by Quinn-With-Two-Ns** [comment]
Tank you again for the contribution, after internal discussion we decided we do not want to support or encourage generic interfaces across our SDKs at this time. We recommend users create specific interfaces for each use case.

https://github.com/temporalio/sdk-python/issues/322

**Pull request closed without merging**
