### PR TITLE
Throw if the server workflow progress is below the progress known to the Workflow Worker

### PR DESCRIPTION
**Pull request by Spikhalskiy**
Add a strict check to the Workflow State machines that guard against using the State Machine that is more advanced than the execution Server is aware of.

### CODE REVIEW

**Review by Sushisource — APPROVED** [review]

**Comment by plfriedman** [comment]
@Spikhalskiy Since upgrading to 1.14, I have had this error thrown a few times. Looking at documentation, I don't see any explanation for what I can/should do to resolve it.  Are there any guidelines, suggestions, trouble-shooting tips I can follow?

**Comment by Spikhalskiy** [comment]
@plfriedman You most likely shouldn't do anything with this error, there is nothing to resolve. 
This usually happens when you have connectivity issues and the worker failed to report progress to the server and gets a task that is already processed. It leads to discarding the "dirty" state from the cache, workflow task failure, and a clean retry with replay of the workflow based on the server history.

Why do you want to resolve it? Is it just an exception in worker logs that bothers you or there is an actual problem that you think is related to this exception?

**Comment by plfriedman** [comment]
@Spikhalskiy I'm still investigating, but from what I can see it looks like it caused the activity execution to fail, which caused the workflow execution to fail, because the max attempts for the activity had been reached.

**Comment by Spikhalskiy** [comment]
@plfriedman it can't lead to a failure of activity execution. This exception and code are related to the processing of Workflow Tasks, not Activity Tasks. Feel free to reach out in Community Slack if you need help with taking a look at the history.

**Comment by plfriedman** [comment]
@Spikhalskiy My activity is querying another workflow for information, I think the exception is coming out of that query
`io.temporal.client.WorkflowQueryException: workflowId='funds_transfer|23335069|funds_transfer|-383185055|MONEY_TO_CREDITCARD', runId='} 
io.temporal.internal.sync.WorkflowStubImpl.throwAsWorkflowFailureExceptionForQuery(WorkflowStubImpl.java:371)
io.temporal.internal.sync.WorkflowStubImpl.query(WorkflowStubImpl.java:274)
io.temporal.internal.sync.WorkflowStubImpl.query(WorkflowStubImpl.java:260)
com.sofi.fundstransfer.workflow.activities.impl.TransferDocumentActivityImpl.getTransferDocument(TransferDocumentActivityImpl.kt:65)
jdk.internal.reflect.GeneratedMethodAccessor162.invoke(Unknown Source)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64)
io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43)
io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:95)
io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:91)
io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:225)
io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:190)
io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:163)
io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.base/java.lang.Thread.run(Thread.java:829)

Caused By: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: java.lang.IllegalStateException: Server history for the workflow is below the progress of the workflow on the worker, the progress needs to be discarded
	at io.temporal.internal.statemachines.WorkflowStateMachines.setStartedIds(WorkflowStateMachines.java:182)
	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleWorkflowTaskImpl(ReplayWorkflowRunTaskHandler.java:179)
	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleQueryWorkflowTask(ReplayWorkflowRunTaskHandler.java:162)
	at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTaskWithQuery(ReplayWorkflowTaskHandler.java:124)
	at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTask(ReplayWorkflowTaskHandler.java:98)
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handleTask(WorkflowWorker.java:293)
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:237)
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:178)
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
 
io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.queryWorkflow(WorkflowServiceGrpc.java:3580)
`

**Comment by plfriedman** [comment]
@Spikhalskiy I think this makes sense then as the activity in question, due to possibly a questionable approach (this is my first Temporal project), is configured for only 1 attempt.  I can work around that for now by handling the exception better.  I really appreciate the quick responses and info!

**Comment by Spikhalskiy** [comment]
@plfriedman Ok, that makes the picture much clear, thank you.

So, what happens here is:
1. Worker has a more advanced state of the workflow that the server knows about.
2. Worker fails a workflow task thinking that it's not a big deal, server can just send a new workflow task. It's a wrong assumption and leads to an explicit query failure.
3. Your activity doesn't expect that query can fail and doesn't try to retry it.
4. Activity is set with maxAttempts = 1, which leads to failure of the workflow.

I will look into 2 and I will make it better.
You meanwhile can take a look at 3 and 4 and make your code a little more tolerant to query failures.

**Comment by plfriedman** [comment]
@Spikhalskiy absolutely, already working on 3; 4 will take a bit longer to re-work because of some other issues.  Glad that I asked and helped you to uncover an experience that needs to be improved (2).  Really enjoying working with Temporal, it's a great product!

**Pull request merged**
