### PR TITLE
Rename UpdateHandle to WorkflowUpdateHandle (💥 - incompatible change)

### PR DESCRIPTION
**Pull request by stephanos**
## What was changed

Renamed `UpdateHandle` to `WorkflowUpdateHandle`.

This is a breaking change.

⚠️ Feature tests are failing; I can update them as a fast follow-up.

## Why?

Consistency. (as discussed previously)

## Checklist

**How was this tested:**

Existing tests.

**Any docs updates needed?**

I checked https://docs.temporal.io/develop/java/message-passing and the `UpdateHandle` type isn't mentioned anywhere.

I also cannot see it in the samples repo ([search](https://github.com/search?q=repo%3Atemporalio%2Fsamples-java%20UpdateHandle&type=code))

The release docs will need to mention this change, though.

### CODE REVIEW

**Review by cretz — APPROVED** [review]
LGTM. I'm adding a 💥 to the PR description since it's backwards incompatible and we will need to clarify in next release notes. May want to wait for @Quinn-With-Two-Ns approval.

**Comment by Quinn-With-Two-Ns** [comment]
LGTM, you'll need to create a `feature` branch and update the code since it did use `UpdateHandle`

**Comment by Quinn-With-Two-Ns** [comment]
Let me know if you need any help with that!

**Review by Quinn-With-Two-Ns — APPROVED** [review]

**Comment by stephanos** [comment]
👀 https://github.com/temporalio/features/pull/532

**Comment by Quinn-With-Two-Ns** [comment]
LGTM!

**Pull request merged**
